[package]
name = "manuvra-flow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
manuvra-chrome = { path = "../manuvra-chrome" }
manuvra-contract = { path = "../manuvra-contract" }
manuvra-jev = { path = "../manuvra-jev" }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
